//! Extend structs for our scheme
#![allow(non_snake_case)]

use ark_bn254::{Fr as Scalar, G1Affine as G1};
use serde::{Deserialize, Serialize};

use crate::modified_serde::*;

/// User's blinded commitment for partial signature
/// C2 = lambda * (m_null * H_null + m_gamma * H_gamma)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UserCommitment {
    #[serde(serialize_with = "serialize_g1", deserialize_with = "deserialize_g1")]
    pub C2: G1,
}

/// Partial signature generated by the Signer
/// Contains two A points and the random scalar e
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PartialSignature {
    #[serde(serialize_with = "serialize_g1", deserialize_with = "deserialize_g1")]
    pub A1: G1,
    #[serde(serialize_with = "serialize_g1", deserialize_with = "deserialize_g1")]
    pub A2_prime: G1,
    #[serde(
        serialize_with = "serialize_scalar",
        deserialize_with = "deserialize_scalar"
    )]
    pub e: Scalar,
}

/// NIZK Proof for BBS+ partial disclosure
/// pi = (A_bar, B_bar, U, s, t, hidden_responses)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct BBSPlusNIZKProof {
    #[serde(serialize_with = "serialize_g1", deserialize_with = "deserialize_g1")]
    pub A_bar: G1,
    #[serde(serialize_with = "serialize_g1", deserialize_with = "deserialize_g1")]
    pub B_bar: G1,
    #[serde(serialize_with = "serialize_g1", deserialize_with = "deserialize_g1")]
    pub U: G1,
    #[serde(
        serialize_with = "serialize_scalar",
        deserialize_with = "deserialize_scalar"
    )]
    pub s: Scalar,
    #[serde(
        serialize_with = "serialize_scalar",
        deserialize_with = "deserialize_scalar"
    )]
    pub t: Scalar,
    /// Store the responses for hidden values (e.g., u_gamma)
    #[serde(
        serialize_with = "serialize_vec_scalar",
        deserialize_with = "deserialize_vec_scalar"
    )]
    pub hidden_responses: Vec<Scalar>,
}